#!/usr/bin/env bash
# ecbuild/CMake configuration for the MONAN-JEDI repository bundle.

monan_jedi_configure_bundle() {
  monan_jedi_load_stack

  require_cmd ecbuild
  require_cmd cmake
  require_cmd python

  if [[ ! -f "${MONAN_JEDI_SOURCE_DIR}/CMakeLists.txt" ]]; then
    log_error "MONAN-JEDI source CMakeLists.txt not found: ${MONAN_JEDI_SOURCE_DIR}/CMakeLists.txt"
    exit 1
  fi

  rm -rf "${MONAN_JEDI_BUILD_DIR}"
  mkdir -p "${MONAN_JEDI_BUILD_DIR}" "${MONAN_JEDI_LOG_ROOT}"
  cd "${MONAN_JEDI_BUILD_DIR}" || {
    log_error "Failed to enter build directory: ${MONAN_JEDI_BUILD_DIR}"
    exit 1
  }

  case "${MONAN_JEDI_MODEL_DOUBLE_PRECISION}" in
    ON|OFF) ;;
    *)
      log_error "Invalid MPAS double precision value: ${MONAN_JEDI_MODEL_DOUBLE_PRECISION}. Use ON or OFF."
      exit 1
      ;;
  esac

  local cache_file="${MONAN_JEDI_BUILD_DIR}/monan-jedi-initial-cache.cmake"
  local after_project_file="${MONAN_JEDI_BUILD_DIR}/monan-jedi-after-project.cmake"
  local python_exe python_prefix python_include python_library


  python_exe="$(command -v python)"
  python_prefix="$(${python_exe} -c 'import sys; print(sys.prefix)')"
  python_include="$(${python_exe} -c 'import sysconfig; print(sysconfig.get_path("include") or "")')"
  python_library="$(${python_exe} -c 'import pathlib, sysconfig; libdir=pathlib.Path(sysconfig.get_config_var("LIBDIR") or ""); ldlib=sysconfig.get_config_var("LDLIBRARY") or ""; path=libdir / ldlib if libdir and ldlib else pathlib.Path(""); print(path if str(path) != "." else "")')"

  cat > "${cache_file}" <<EOF
# Generated by scripts/lib/configure.sh.
set(Python3_EXECUTABLE "${python_exe}" CACHE FILEPATH "" FORCE)
set(Python_EXECUTABLE "${python_exe}" CACHE FILEPATH "" FORCE)
set(PYTHON_EXECUTABLE "${python_exe}" CACHE FILEPATH "" FORCE)
set(Python3_ROOT_DIR "${python_prefix}" CACHE PATH "" FORCE)
set(Python3_INCLUDE_DIR "${python_include}" CACHE PATH "" FORCE)
set(_Python3_INCLUDE_DIR "${python_include}" CACHE PATH "" FORCE)
set(Python3_FIND_STRATEGY LOCATION CACHE STRING "" FORCE)
set(Python3_FIND_REGISTRY NEVER CACHE STRING "" FORCE)
set(Python3_FIND_FRAMEWORK NEVER CACHE STRING "" FORCE)
set(MONAN_JEDI_INITIAL_CACHE_LOADED ON CACHE BOOL "" FORCE)
EOF

  if [[ -n "${python_library}" && -f "${python_library}" ]]; then
    cat >> "${cache_file}" <<EOF
set(Python3_LIBRARY "${python_library}" CACHE FILEPATH "" FORCE)
set(Python3_LIBRARIES "${python_library}" CACHE STRING "" FORCE)
EOF
  fi

  cat > "${after_project_file}" <<'EOF'
# Generated by scripts/lib/configure.sh.
if(NOT MONAN_JEDI_AFTER_PROJECT_INCLUDE_DONE)
  set(MONAN_JEDI_AFTER_PROJECT_INCLUDE_DONE TRUE CACHE INTERNAL "")
  find_package(ip CONFIG QUIET)
  if(TARGET ip::ip_d)
    message(STATUS "MONAN-JEDI after-project include: ip::ip_d is available")
  else()
    message(STATUS "MONAN-JEDI after-project include: ip::ip_d not available; continuing")
  endif()
endif()
EOF

  monan_jedi_record_environment_snapshot "${MONAN_JEDI_LOG_ROOT}/04_configure_environment.log"

  log_info "Configuring MONAN-JEDI bundle"
  log_info "  source=${MONAN_JEDI_SOURCE_DIR}"
  log_info "  build=${MONAN_JEDI_BUILD_DIR}"

  ecbuild "${MONAN_JEDI_SOURCE_DIR}" \
    "-C${cache_file}" \
    "-DCMAKE_PROJECT_INCLUDE=${after_project_file}" \
    "-DCMAKE_C_COMPILER=${CC}" \
    "-DCMAKE_CXX_COMPILER=${CXX}" \
    "-DCMAKE_Fortran_COMPILER=${FC}" \
    "-DMPI_C_COMPILER=${MPICC}" \
    "-DMPI_CXX_COMPILER=${MPICXX}" \
    "-DMPI_Fortran_COMPILER=${MPIFC}" \
    "-DPython3_EXECUTABLE=${python_exe}" \
    "-DPython_EXECUTABLE=${python_exe}" \
    "-DPYTHON_EXECUTABLE=${python_exe}" \
    "-DBUILD_MPAS=ON" \
    "-DBUILD_GSIBEC=OFF" \
    "-DMPAS_DOUBLE_PRECISION=${MONAN_JEDI_MODEL_DOUBLE_PRECISION}" \
    2>&1 | tee "${MONAN_JEDI_LOG_ROOT}/04_ecbuild.log"
}
