#!/usr/bin/env bash
# ecbuild/CMake configuration.
#
# Purpose:
#   Configure the MONAN-JEDI reduced MPAS-JEDI bundle build tree with ecbuild
#   and CMake.
#
# Responsibilities:
#   - load the configured stack environment
#   - validate configure-time tools
#   - recreate the build directory
#   - generate CMake helper files for Python discovery and late project checks
#   - record an environment snapshot
#   - run ecbuild with explicit compiler, MPI and Python settings

monan_jedi_configure_bundle() {
  # Configure must run inside the same stack environment used for build/test.
  monan_jedi_load_stack

  require_cmd ecbuild
  require_cmd cmake
  require_cmd python

  if [[ ! -d "${JEDI_BUNDLE_SRC_DIR}/.git" ]]; then
    log_error "JEDI bundle source not found: ${JEDI_BUNDLE_SRC_DIR}"
    exit 1
  fi

  # Recreate the build directory to avoid stale CMake cache state.
  rm -rf "${JEDI_BUNDLE_BUILD_DIR}"
  mkdir -p "${JEDI_BUNDLE_BUILD_DIR}" "${MONAN_JEDI_LOG_ROOT}"
  cd "${JEDI_BUNDLE_BUILD_DIR}" || {
    log_error "Failed to enter build directory: ${JEDI_BUNDLE_BUILD_DIR}"
    exit 1
  }

  local cache_file="${JEDI_BUNDLE_BUILD_DIR}/monan-jedi-initial-cache.cmake"
  local after_project_file="${JEDI_BUNDLE_BUILD_DIR}/monan-jedi-after-project.cmake"
  local python_exe python_prefix python_include python_library

  # Use the Python executable provided by the loaded stack environment.
  python_exe="$(command -v python)"

  # Capture Python metadata directly from the selected interpreter so CMake does
  # not accidentally discover another Python installation.
  python_prefix="$(${python_exe} - <<'PY'
import sys
print(sys.prefix)
PY
)"
  python_include="$(${python_exe} - <<'PY'
import sysconfig
print(sysconfig.get_path('include') or '')
PY
)"
  python_library="$(${python_exe} - <<'PY'
import pathlib
import sysconfig
libdir = pathlib.Path(sysconfig.get_config_var('LIBDIR') or '')
ldlib = sysconfig.get_config_var('LDLIBRARY') or ''
path = libdir / ldlib if libdir and ldlib else pathlib.Path('')
print(path if str(path) != '.' else '')
PY
)"

  # Generate an initial cache that only sets cache variables. It must not call
  # find_package(), because early package discovery can happen before the JEDI
  # bundle project has initialized its environment.
  cat > "${cache_file}" <<EOF
# Generated by scripts/lib/configure.sh.
set(Python3_EXECUTABLE "${python_exe}" CACHE FILEPATH "" FORCE)
set(Python_EXECUTABLE "${python_exe}" CACHE FILEPATH "" FORCE)
set(PYTHON_EXECUTABLE "${python_exe}" CACHE FILEPATH "" FORCE)
set(Python3_ROOT_DIR "${python_prefix}" CACHE PATH "" FORCE)
set(Python3_INCLUDE_DIR "${python_include}" CACHE PATH "" FORCE)
set(_Python3_INCLUDE_DIR "${python_include}" CACHE PATH "" FORCE)
set(Python3_FIND_STRATEGY LOCATION CACHE STRING "" FORCE)
set(Python3_FIND_REGISTRY NEVER CACHE STRING "" FORCE)
set(Python3_FIND_FRAMEWORK NEVER CACHE STRING "" FORCE)
set(MONAN_JEDI_INITIAL_CACHE_LOADED ON CACHE BOOL "" FORCE)
EOF

  # Add Python library hints only when a real library path is available.
  if [[ -n "${python_library}" && -f "${python_library}" ]]; then
    cat >> "${cache_file}" <<EOF
set(Python3_LIBRARY "${python_library}" CACHE FILEPATH "" FORCE)
set(Python3_LIBRARIES "${python_library}" CACHE STRING "" FORCE)
EOF
  fi

  # Generate a late CMake include for project-specific checks after project().
  cat > "${after_project_file}" <<'EOF'
# Generated by scripts/lib/configure.sh.
if(NOT MONAN_JEDI_AFTER_PROJECT_INCLUDE_DONE)
  set(MONAN_JEDI_AFTER_PROJECT_INCLUDE_DONE TRUE CACHE INTERNAL "")
  find_package(ip CONFIG QUIET)
  if(TARGET ip::ip_d)
    message(STATUS "MONAN-JEDI after-project include: ip::ip_d is available")
  else()
    message(STATUS "MONAN-JEDI after-project include: ip::ip_d not available; continuing")
  endif()
endif()
EOF

  if [[ ! -f "${cache_file}" ]]; then
    log_error "Initial cache file was not created: ${cache_file}"
    exit 1
  fi

  if [[ ! -f "${after_project_file}" ]]; then
    log_error "After-project CMake include was not created: ${after_project_file}"
    exit 1
  fi

  # Protect the initial cache from early package discovery.
  if grep -Eq '^[[:space:]]*find_package[[:space:]]*\(' "${cache_file}"; then
    log_error "Initial cache contains forbidden early find_package(): ${cache_file}"
    exit 1
  fi

  monan_jedi_record_environment_snapshot "${MONAN_JEDI_LOG_ROOT}/04_configure_environment.log"

  log_info "Configuring MONAN-JEDI reduced MPAS-JEDI bundle"
  log_info "  source=${JEDI_BUNDLE_SRC_DIR}"
  log_info "  build=${JEDI_BUNDLE_BUILD_DIR}"
  log_info "  initial_cache=${cache_file}"
  log_info "  after_project=${after_project_file}"

  # Run ecbuild with explicit compiler, MPI and Python settings to reduce
  # ambiguity on CrayPE systems.
  ecbuild "${JEDI_BUNDLE_SRC_DIR}" \
    "-C${cache_file}" \
    "-DCMAKE_PROJECT_INCLUDE=${after_project_file}" \
    "-DCMAKE_C_COMPILER=${CC}" \
    "-DCMAKE_CXX_COMPILER=${CXX}" \
    "-DCMAKE_Fortran_COMPILER=${FC}" \
    "-DMPI_C_COMPILER=${MPICC}" \
    "-DMPI_CXX_COMPILER=${MPICXX}" \
    "-DMPI_Fortran_COMPILER=${MPIFC}" \
    "-DPython3_EXECUTABLE=${python_exe}" \
    "-DPython_EXECUTABLE=${python_exe}" \
    "-DPYTHON_EXECUTABLE=${python_exe}" \
    "-DBUILD_MPAS=ON" \
    "-DBUILD_GSIBEC=OFF" \
    2>&1 | tee "${MONAN_JEDI_LOG_ROOT}/04_ecbuild.log"
}
