#!/usr/bin/env bash
# Login-node-safe CTest handling.
#
# Purpose:
#   Execute a restricted subset of CTest cases considered safe for execution on
#   a JACI login node. This avoids running large MPI tests directly on the login
#   environment.
#
# Requires:
#   A completed build tree generated by configure and build.
#
# Produces:
#   ${MONAN_JEDI_LOG_ROOT}/06_ctest.log
#
# Expected result:
#   ctest exits with status zero and the selected tests pass.

monan_jedi_test_login() {
  monan_jedi_load_stack
  require_cmd ctest

  local login_safe_regex="${MONAN_JEDI_CTEST_REGEX:-^mpasjedi_coding_norms$}"

  if [[ ! -f "${JEDI_BUNDLE_BUILD_DIR}/CTestTestfile.cmake" ]]; then
    log_error "Build tree does not contain CTestTestfile.cmake: ${JEDI_BUNDLE_BUILD_DIR}"
    exit 1
  fi

  cd "${JEDI_BUNDLE_BUILD_DIR}"

  ctest --output-on-failure \
    -j "${MONAN_JEDI_CTEST_JOBS}" \
    -R "${login_safe_regex}" \
    2>&1 | tee "${MONAN_JEDI_LOG_ROOT}/06_ctest.log"
}
