#!/usr/bin/env bash
# =============================================================================
# 04_configure_mpas_jedi.sh
# =============================================================================
# Configure the reduced MPAS-JEDI-only bundle on JACI.
# =============================================================================

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=00_common.sh
source "${script_dir}/00_common.sh"

require_cmd ecbuild
require_cmd cmake
require_cmd python
load_monan_jedi_stack

if [[ ! -d "${JEDI_BUNDLE_SRC_DIR}/.git" ]]; then
  log_error "JEDI bundle source not found: ${JEDI_BUNDLE_SRC_DIR}"
  log_error "Run scripts/02_prepare_jedi_bundle.sh first."
  exit 1
fi

rm -rf "${JEDI_BUNDLE_BUILD_DIR}"
mkdir -p "${JEDI_BUNDLE_BUILD_DIR}" "${MONAN_JEDI_LOG_ROOT}"
cd "${JEDI_BUNDLE_BUILD_DIR}"

cache_file="${JEDI_BUNDLE_BUILD_DIR}/monan-jedi-initial-cache.cmake"
after_project_file="${JEDI_BUNDLE_BUILD_DIR}/monan-jedi-after-project.cmake"
python_exe="$(command -v python)"
python_prefix="$(${python_exe} - <<'PY'
import sys
print(sys.prefix)
PY
)"
python_include="$(${python_exe} - <<'PY'
import sysconfig
print(sysconfig.get_path('include') or '')
PY
)"
python_library="$(${python_exe} - <<'PY'
import pathlib, sysconfig
libdir = pathlib.Path(sysconfig.get_config_var('LIBDIR') or '')
ldlib = sysconfig.get_config_var('LDLIBRARY') or ''
path = libdir / ldlib if libdir and ldlib else pathlib.Path('')
print(path if str(path) != '.' else '')
PY
)"

cat > "${cache_file}" <<EOF
# Generated by scripts/04_configure_mpas_jedi.sh for JACI.
set(Python3_EXECUTABLE "${python_exe}" CACHE FILEPATH "" FORCE)
set(Python_EXECUTABLE "${python_exe}" CACHE FILEPATH "" FORCE)
set(PYTHON_EXECUTABLE "${python_exe}" CACHE FILEPATH "" FORCE)
set(Python3_ROOT_DIR "${python_prefix}" CACHE PATH "" FORCE)
set(Python3_INCLUDE_DIR "${python_include}" CACHE PATH "" FORCE)
set(_Python3_INCLUDE_DIR "${python_include}" CACHE PATH "" FORCE)
set(Python3_FIND_STRATEGY LOCATION CACHE STRING "" FORCE)
set(Python3_FIND_REGISTRY NEVER CACHE STRING "" FORCE)
set(Python3_FIND_FRAMEWORK NEVER CACHE STRING "" FORCE)
EOF

if [[ -n "${python_library}" && -f "${python_library}" ]]; then
  cat >> "${cache_file}" <<EOF
set(Python3_LIBRARY "${python_library}" CACHE FILEPATH "" FORCE)
set(Python3_LIBRARIES "${python_library}" CACHE STRING "" FORCE)
EOF
fi

cat > "${after_project_file}" <<'EOF'
# Generated by scripts/04_configure_mpas_jedi.sh for JACI.
if(NOT MONAN_JEDI_AFTER_PROJECT_INCLUDE_DONE)
  set(MONAN_JEDI_AFTER_PROJECT_INCLUDE_DONE TRUE CACHE INTERNAL "")
  find_package(ip CONFIG QUIET)
  if(TARGET ip::ip_d)
    message(STATUS "MONAN-JEDI after-project include: ip::ip_d is available")
  else()
    message(STATUS "MONAN-JEDI after-project include: ip::ip_d not available; continuing")
  endif()
endif()
EOF

record_environment_snapshot "${MONAN_JEDI_LOG_ROOT}/04_configure_environment.log"

cmake_args=(
  "-C${cache_file}"
  "-DCMAKE_PROJECT_INCLUDE=${after_project_file}"
  "-DCMAKE_C_COMPILER=${CC}"
  "-DCMAKE_CXX_COMPILER=${CXX}"
  "-DCMAKE_Fortran_COMPILER=${FC}"
  "-DMPI_C_COMPILER=${MPICC}"
  "-DMPI_CXX_COMPILER=${MPICXX}"
  "-DMPI_Fortran_COMPILER=${MPIFC}"
  "-DPython3_EXECUTABLE=${python_exe}"
  "-DPython_EXECUTABLE=${python_exe}"
  "-DPYTHON_EXECUTABLE=${python_exe}"
  "-DBUILD_MPAS=ON"
  "-DBUILD_GSIBEC=OFF"
)

log_info "Configuring MPAS-JEDI-only bundle with ecbuild"
log_info "  source=${JEDI_BUNDLE_SRC_DIR}"
log_info "  build=${JEDI_BUNDLE_BUILD_DIR}"
log_info "  log=${MONAN_JEDI_LOG_ROOT}/04_ecbuild.log"

ecbuild "${JEDI_BUNDLE_SRC_DIR}" "${cmake_args[@]}" \
  2>&1 | tee "${MONAN_JEDI_LOG_ROOT}/04_ecbuild.log"

if grep -Eq '^[[:space:]]*find_package[[:space:]]*\(' "${cache_file}"; then
  log_error "Initial cache contains forbidden early find_package()."
  exit 1
fi

log_info "MPAS-JEDI configure completed."
